#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-timecop
Version  : 0.8.1
Release  : 8
URL      : https://rubygems.org/downloads/timecop-0.8.1.gem
Source0  : https://rubygems.org/downloads/timecop-0.8.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
# timecop
[![Build Status](https://secure.travis-ci.org/travisjeffery/timecop.png)](http://travis-ci.org/travisjeffery/timecop)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n timecop-0.8.1
gem spec %{SOURCE0} -l --ruby > rubygem-timecop.gemspec

%build
gem build rubygem-timecop.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
timecop-0.8.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/timecop-0.8.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/README.markdown
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/lib/timecop.rb
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/lib/timecop/time_extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/lib/timecop/time_stack_item.rb
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/lib/timecop/timecop.rb
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/lib/timecop/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/test/time_stack_item_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/test/timecop_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/test/timecop_without_date_but_with_time_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/timecop-0.8.1/test/timecop_without_date_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/timecop-0.8.1.gemspec
