#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-timecop
Version  : 0.7.4
Release  : 3
URL      : https://rubygems.org/downloads/timecop-0.7.4.gem
Source0  : https://rubygems.org/downloads/timecop-0.7.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-metaclass
BuildRequires : rubygem-minitest
BuildRequires : rubygem-mocha
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
# timecop
[![Build Status](https://secure.travis-ci.org/travisjeffery/timecop.png)](http://travis-ci.org/travisjeffery/timecop)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n timecop-0.7.4
gem spec %{SOURCE0} -l --ruby > rubygem-timecop.gemspec

%build
gem build rubygem-timecop.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
timecop-0.7.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/timecop-0.7.4
ruby -v -I.:lib:test test*/test_*.rb
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/timecop-0.7.4.gem
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Date/cdesc-Date.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/DateTime/cdesc-DateTime.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Time/cdesc-Time.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/SafeModeException/cdesc-SafeModeException.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/SafeModeException/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/TimeStackItem/cdesc-TimeStackItem.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/baseline%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/baseline%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/baseline-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/cdesc-Timecop.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/freeze-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/return-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/return-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/return_to_baseline-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/return_to_baseline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/safe_mode%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/safe_mode%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/scale-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/send_travel-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/Timecop/travel-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/page-LICENSE.ri
/usr/lib64/ruby/gems/2.2.0/doc/timecop-0.7.4/ri/page-README_markdown.ri
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/README.markdown
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/lib/timecop.rb
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/lib/timecop/time_extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/lib/timecop/time_stack_item.rb
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/lib/timecop/timecop.rb
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/lib/timecop/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/test/run_tests.sh
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/test/time_stack_item_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/test/timecop_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/test/timecop_without_date_but_with_time_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/timecop-0.7.4/test/timecop_without_date_test.rb
/usr/lib64/ruby/gems/2.2.0/specifications/timecop-0.7.4.gemspec
